jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra

      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Execute collection
        run: newman run ./login.json -e ./environment.json -g ./globals.json -r htmlextra --reporter-htmlextra-export ./result/report.html

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./result/report.html

               